### ISSUE TITLE
FixedPollingStrategy blocks if remote source is unavailable

### ISSUE THREAD

**Issue by fcappi** [Netflix/archaius#548] opened 2018-05-05 14:29 UTC
Hi,
Currently, when you try to instantiate a PollingDynamicConfig, using the FixedPollingStrategy, the execution stucks on the following while(true) condition if the remote source is unavailable:

https://github.com/Netflix/archaius/blob/3a56eb807cf1465212e5d65603a54b24dbeea8a4/archaius2-core/src/main/java/com/netflix/archaius/config/polling/FixedPollingStrategy.java#L44-L72

The problem is that if you are using Guice to provide the property source, it will block Guice from resolving this dependency.

My suggestion is to remove the while(true) and let the scheduler handle the attempts to read from the remote source.

What do you guys think ?

**Comment by siddheshshirsat** [comment] 2019-12-24 02:13
I don't think the issue is specific to Guice or a remote service. Any Exception thrown from the reader's call() method will result in an indefinite loop.

https://github.com/Netflix/archaius/blob/3a56eb807cf1465212e5d65603a54b24dbeea8a4/archaius2-core/src/main/java/com/netflix/archaius/config/PollingDynamicConfig.java#L82

I agree that even the first attempt to perform the update should be done with the ScheduledExecutorService.

**Comment by siddheshshirsat** [comment] 2019-12-24 20:45
The first attempt to perform the update should be done with the ScheduledExecutorService results in race conditions in reading values immediately after creating the config instance.

One solution could be to just get rid of the infinite loop block and do a best-attempt reading for the first time and then defer the rest of the calls to the reader to the ScheduledExecutorService.

I have the fix ready for this in my local workspace but don't have permissions to raise a CR or push to a remote branch. Can someone help with that?

**Comment by siddheshshirsat** [comment] 2019-12-27 18:35
https://github.com/Netflix/archaius/compare/2.x...siddheshshirsat:Issue548#diff-ab5b04cb7b29555aa4347f61a943e55eR46

**Comment by BenderRodrigez** [comment] 2020-07-25 20:08
Nice catch! :+1:  I wish I looked here before production incident...

**Comment by siddheshshirsat** [comment] 2020-07-25 20:26
Thank you.

**Comment by rgallardo-netflix** [comment] 2023-02-15 22:58
Won't fix.

Although this issue was reported against v1, v2 has equivalent behavior and this is a design choice. We believe that allowing an application to come up without being able to receive remote config overrides has the potential of causing even worse issues, because any config that is only read at boot time would be silently set to the "non-overridden" value, causing hard-to-debug problems from an inconsistent fleet.

**Closed by rgallardo-netflix** 2023-02-15 22:58 UTC
